const medHeader: string[] = [
  'SUBSTNCIA',
  'CNPJ',
  'LABORATRIO',
  'CDIGO GGREM',
  'REGISTRO',
  'EAN 1',
  'EAN 2',
  'EAN 3',
  'PRODUTO',
  'APRESENTAO',
  'CLASSE TERAPUTICA',
  'TIPO DE PRODUTO STATUS DO PRODUTO',
  'REGIME DE PREO',
  'PF Sem Impostos',
  'PF 0',
  'PF 12',
  'PF 17',
  'PF 17 ALC',
  'PF 175',
  'PF 175 ALC',
  'PF 18',
  'PF 18 ALC',
  'PF 20',
  'PMC 0',
  'PMC 12',
  'PMC 17',
  'PMC 17 ALC',
  'PMC 175',
  'PMC 175 ALC',
  'PMC 18',
  'PMC 18 ALC',
  'PMC 20',
  'RESTRIO HOSPITALAR',
  'CAP',
  'CONFAZ 87',
  'ICMS 0',
  'ANLISE RECURSAL',
  'LISTA DE CONCESSO DE CRDITO TRIBUTRIO PISCOFINS',
  'COMERCIALIZAO 2020',
  'TARJA'
];

export default medHeader;